# Generated by Django 5.1.4 on 2024-12-12 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0004_alter_clientes_cedula_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Fecha_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre del cliente:'),
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='ventas_clientes',
        ),
    ]
