# Generated by Django 5.1.4 on 2024-12-12 12:52

import Ventasapp.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0005_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[Ventasapp.validadores.validar_cedula]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre del Empleado : '),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(max_length=10, validators=[Ventasapp.validadores.validar_telefono]),
        ),
    ]
