# Generated by Django 5.1.4 on 2024-12-12 13:09

import Ventasapp.validadores
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0007_alter_empresas_nombre_alter_empresas_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='fecha_ingreso',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='empresas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='fecha_inicio_actividades',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre de la empresa : '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name=' Nombre del producto : '),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[Ventasapp.validadores.validar_cedula]),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre del proveedor : '),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(max_length=10, validators=[Ventasapp.validadores.validar_telefono]),
        ),
    ]
