# Generated by Django 5.1.4 on 2024-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0008_rename_fecha_ingreso_productos_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada'), ('DEVUELTA', 'Devuelta')], default='ACTIVA', max_length=10),
        ),
        migrations.AlterModelTable(
            name='factura',
            table=None,
        ),
    ]
