# Generated by Django 5.1.4 on 2024-12-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0009_alter_factura_options_factura_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_factura',
            field=models.CharField(choices=[('DATOS_COMPLETOS', 'Con Datos Completos'), ('CONSUMIDOR_FINAL', 'Consumidor Final')], default='DATOS_COMPLETOS', max_length=20),
        ),
    ]
