# Generated by Django 5.1.4 on 2024-12-18 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0011_alter_factura_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='caracteristicas_categoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre de la empresa:'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad_stock',
            field=models.IntegerField(verbose_name='Cantidad en stock:'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre del producto:'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto:'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre del proveedor:'),
        ),
        migrations.AlterModelTable(
            name='empresas',
            table='empresas',
        ),
        migrations.AlterModelTable(
            name='factura',
            table='facturas',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='proveedores',
        ),
    ]
